version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: postgres_db
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - pg_data:/var/lib/postgresql/data

    backend:
        build: ./backend
        container_name: backend_app
        restart: always
        depends_on:
            - postgres
        env_file:
            - .env
        environment:
            DATABASE_URL: ${DATABASE_URL}
        ports:
            - '${API_PORT}:8000'
        command: ['sh', '-c', 'npx prisma migrate deploy && node dist/main']

    frontend:
        build: ./frontend
        container_name: frontend_app
        restart: always
        depends_on:
            - backend
        ports:
            - '${FRONTEND_PORT}:3000'
        command: ['npm', 'run', 'dev']

volumes:
    pg_data:
